theme: jekyll-theme-modernist
title: Kingtog Technology Co., Ltd 
description:  To bring people-oriented technology solutions that positively impact lives. 
company_name: Huizhou Kingtog Technology Co., Ltd 
company_nickname: Kingtog Technology
app_name_food_tracker: Food Tracker
app_name_air_transfer: Air Transfer
contact_email: service_hotheadlion@outlook.com
show_downloads: false
domain_name: kingtog.com

